[Feat/#2] 1주차 과제
AND-SOPT-ANDROID/jongmyoung-kim pull request #3
Opened 2024-10-10 17:35 UTC by jm991014

## Related issue 🛠
- closed #2

## Work Description ✏️
필수 과제
- 회원가입 뷰 구현
- 로그인 뷰 구현
- MY 뷰 구현

심화 과제
- 자동 로그인 (SharedPreferences 적용)
- TextField Custom (Single line, keyboard action)
- 클릭 Ripple 제거
- 키보드 IME padding

## Screenshot 📸
<img src="" width="360"/>

- 회원가입

[sign_up.webm](https://github.com/user-attachments/assets/397693db-932e-47da-9ae0-0813b95bc6ff)

- 로그인

[sign_in.webm](https://github.com/user-attachments/assets/6b316542-2d84-493b-a311-a835b803aa2f)

- 자동 로그인(MyPage)

[my_page.webm](https://github.com/user-attachments/assets/8a777225-a809-4aef-bfa5-cb7939dfd385)

## Uncompleted Tasks 😅
- [ ] ViewModel 적용 (미룬이라 죄송합니다.. 시간 남을 때 적용하겠습니다ㅠㅠ)
- [ ] 로그아웃 (이거 못 봤네용.. 바로 하겠습니다)
- [ ] MyPage 기본 프로필 사진 적용 (이건.. 나중에 따서 적용하겠습니다)
- [ ] TextField Custom시 trailIcon 속성에 의해 할당되는 공간 제거 (이거는 BasicTextField나 다른 함수를 써야하는지, 더 좋은 방안이 있다면 피드백 부탁드립니다!)

## To Reviewers 📢
- 컴포넌트화, 로직, 그 어떤것도 괜찮으니 피드백 해주시면 감사하겠습니다...!
- 원래는 실제 앱과 비교해가며 TextField에 입력된 값을 관측하여 에러 문구를 띄우는 걸 구현해보려 했는데.. 시간을 너무 잡아먹어서 지웠슴당.. 미처 못지운건 변명타임 주시면 해명하겠습니다 ㅋ
- 다들.. 너무 잘하셔서 부끄럽읍니다..

2024-10-11 03:02 UTC, unam98 reviewed
안녕하세요 명예 ob 리뷰어로 참여하게된 김우남이라고 합니다~! 👍🏻

전반적으로 하드코딩이 많이 돼있는 것으로 보이는데 스트링 리소스로 관리해주시면 좋을 것 같습니다 :)

2024-10-11 03:02 UTC, unam98 commented on app/src/main/java/org/sopt/and/presentation/main/mypage/components/MyPageTicket.kt
> +            description = "첫 결제 시 첫 달 100원!"
하드 코딩보단 스트링 리소스로 관리하면 더 좋을 것 같아요!

2024-10-11 03:02 UTC, unam98 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignUpScreen.kt
> +//                    if (isButtonEnabled) WavveMain else LightGray
사용하지 않는 코드는 제거하거나 의도가 있다면 설명을 남겨주시는 게 좋을 것 같아요!

2024-10-11 03:02 UTC, unam98 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInActivity.kt
> +                putBoolean("is_logged_in", true)
key값은 상수로 빼서 관리하면 좋을 것 같아요!

2024-10-11 03:02 UTC, unam98 commented on app/src/main/java/org/sopt/and/presentation/main/mypage/MyPageScreen.kt
> +                text = "${userEmail}님",
이 부분도 스트링 리소스로 분리하면 좋을 것 같아요~!

2024-10-11 04:11 UTC, boiledEgg-s requested changes
너무 잘하시는데요?? 하드코딩만 없애면 될 것 같아요!
우리 조 무섭다,,,

2024-10-11 04:11 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInScreen.kt
> +    onSignInClick: (String, String) -> Unit
컴포저블 선언할 때 인자의 순서는 다음과 같이 선언하는게 일반적입니다:
1. 필수 인자
2. 수정자
3. 선택 인자

여기에선 마지막 인자가 고차 함수이다 보니까 오류 메시지를 안 띄워주는거 같은데, 
왠만하면 컴포즈 컨벤션을 지키는게 좋을 것 같아요!

2024-10-11 04:11 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/presentation/authentication/SignUpScreen.kt
> +        string1 = "이메일과 비밀번호",
명예오비분께서도 언급하셨지만 하드코딩은 지양합시다!
저는 Preview에서 사용하는게 아니라면 왠만하면 리소스화 하는 편이에요~

2024-10-11 04:11 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/presentation/authentication/components/CustomTextField.kt
> +    cursorColor: Color = WavveMain
수정자 위치 수정 예시입니다!
```suggestion
    value: String,
    hint: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier,
    isPassword: Boolean = false,
    visualTransformation: VisualTransformation = VisualTransformation.None,
    shape: Shape = RoundedCornerShape(8.dp),
    cursorColor: Color = WavveMain
```

2024-10-11 04:11 UTC, boiledeggg commented on app/src/main/java/org/sopt/and/presentation/authentication/components/SnsAccountTab.kt
> +            )
반복되는 뷰는 리스트화하는게 더 가독성 측면에서 좋을 것 같아요!!
혹은 이런 선택지를 제공하는 뷰는 enum class로 리스트를 관리하는 것도 방법이에요!

2024-10-11 05:54 UTC, kangyein9892 approved these changes

2024-10-11 05:54 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInScreen.kt
> +//        )
AlertText 사용한 부분(여기 말고도 밑에 86-89)도 주석 처리 되어있던데 이 부분은 추후 사용하시려고 일단 주석처리 해놓으신 걸까요? 사용하지 않는 거면 아예 빼는 게 좋을 것 같고, 아니라면 설명이 있는 게 좋을 것 같아서요 !

2024-10-11 05:54 UTC, kangyein9892 commented on app/src/main/java/org/sopt/and/presentation/authentication/components/CustomTopBar.kt
> + */
주석으로 설명이 적혀있으니까 어떤 컴포넌트인지 알아서 좋은 것 같아요!

2024-10-11 05:58 UTC, kangyein9892 approved these changes
우리 조 진짜 잘한다... 짱짱... 배울게 많아요... 알차요...!!

2024-10-11 06:35 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/presentation/authentication/components/CustomTopBar.kt
> +                    // TODO: 회원가입 취소 Dialog 표시
웨이브 어플을 유심히 보셨군요!!

2024-10-11 06:36 UTC, serioushyeon commented on app/src/main/java/org/sopt/and/presentation/authentication/components/SnsAccountTab.kt
> +            contentDescription = null
description이 있으면 좋을 것 같아요!

2024-10-11 06:38 UTC, serioushyeon approved these changes

2024-10-11 10:09 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/main/mypage/components/MyPageTicket.kt
> +            description = "첫 결제 시 첫 달 100원!"
넵 수정하겠습니다!

2024-10-11 10:09 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignUpScreen.kt
> +//                    if (isButtonEnabled) WavveMain else LightGray
추후 사용하려 남겨놨는데 설명이 없었네요.. 수정하겠읍니닷

2024-10-11 10:10 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInActivity.kt
> +                putBoolean("is_logged_in", true)
이 부분도.. 수정해놓겠습니다!!

2024-10-11 10:10 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInScreen.kt
> +    onSignInClick: (String, String) -> Unit
처음 알았네요.. 감사합니당~

2024-10-11 10:10 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignUpScreen.kt
> +        string1 = "이메일과 비밀번호",
넵 참고해서 수정해놓겠습니다~!!

2024-10-11 10:11 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/components/SnsAccountTab.kt
> +            )
조장님 코드 보고 배워갑니다 앞으론 그렇게 하겠읍니다~

2024-10-11 10:12 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/components/SnsAccountTab.kt
> +            contentDescription = null
넵~~!! 수정해놓겠습니다!

2024-10-11 10:15 UTC, jm991014 commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInScreen.kt
> +//        )
맞아요.. 구현하다 스낵바로 처리했는데 나중에 다시 시도해보려구요 ㅎㅎ 설명 추가해놓겠습니다!

2024-10-14 00:20 UTC, boiledEgg-s approved these changes
수정까지 너무 수고 많으셨습니다~
2주차도 화이팅!

2024-10-14 00:20 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInActivity.kt
> +            val snackbarMessage = intent.getStringExtra("snackbar_message") ?: ""
Intent 키나 Preference의 키와 같이 여러 군데에서 쓰이는 문자열은 상수화하거나 리소스화하는게 좋아요!!

2024-10-14 00:20 UTC, boiledEgg-s commented on app/src/main/java/org/sopt/and/presentation/authentication/components/SnsAccountTab.kt
> +}
이런건 파일 분리를 해주는게 좋을 것 같습니다!

2024-10-14 07:13 UTC, merged

2024-10-16 09:47 UTC, jihyunniiii reviewed
고생하셨습니다 ~

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.ANDANDROID"/>
지금 application에서 theme를 설정해주고 있죠?
이렇게 설정하면 해당 theme이 기본 theme가 됩니다.
activity에서 기본 theme을 사용하고자한다면, activity에 theme를 중복으로 설정해주지 않아도 됩니다.

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInActivity.kt
> +            val email = intent.getStringExtra("email") ?: ""
val email = intent.getStringExtra("email").orEmpty()
이런식으로 작성하실 수도 있습니다.

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInActivity.kt
> +                                coroutineScope
인자가 많은 경우 named parameter를 사용하면 가독성을 더 높일 수 있습니다 !

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInScreen.kt
> +                if (it.length <= Constants.MAX_PASSWORD) passwordInput = it
허얼 좋네요 ~

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/SignInScreen.kt
> +        CustomTextField(
지금 Email과 Password TextField에서 일부 값을 제외하고 나머지 형태가 모두 동일한데요. (hint, MAX 값 등)
이 경우에 enum class를 통해 Type화 해보는 것도 방법이 될 수 있겠네요! (코드가 더 간결해 질 것 같아요! 물론 확장성을 생각해서는 이대로 두는 것도 괜찮을 것 같습니다 ~)

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/SignUpActivity.kt
> +                }
showSnackbar 함수 내부에 when 문을 넣어도 될 것 같아요! when문에서 모두 snackbar를 보여주는 역할을 하니까요

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/SignUpActivity.kt
> +}
다른 분들 리뷰에서와 마찬가지로 Regex 객체 생성은 CPU를 많이 요구하는 무거운 작업 중 하나입니다.
그렇기 때문에 지금처럼 작성하시게 되면 해당 함수를 불러올 때마다 객체를 생성하게 되므로 CPU에 무리가 갈 수도 있는데요!
싱글톤 패턴을 통해 객체를 미리 만들어두시는 걸 추천드립니다.

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/authentication/components/AlertText.kt
> +fun AlertText(
이 부분까지 같이 TextField에 넣어서 컴포넌트를 만드는 방법도 있을 것 같네요~

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/main/mypage/MyPageActivity.kt
> +            val snackbarMessage = intent.getStringExtra("snackbar_message") ?: ""
요것도 상수화 해주면 좋겠네요

2024-10-16 09:47 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/main/mypage/components/MyPageContents.kt
> +        Pair("관심 에디터Pick", "관심 에디터Pick이 없어요.")
Pair 사용 좋네용